# Site settings
title: Gametoy project
email: adrienmar@kickmaker.net
description: Gametoy project is a very basic woodbox with LEDs, button, buzzer and display to play games

baseurl: /gametoy/
url: https://adri1mart1.github.io/

github_username: adri1mart1

# Build settings
markdown: kramdown
